### ISSUE TITLE
phpGettersSetters error: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by theophane-girard** [cvergne/vscode-php-getters-setters#11]
Hello :) 

When i click on "Insert getter/setter" i get following error message

![image](https://user-images.githubusercontent.com/11314829/117420062-837f4300-af1d-11eb-88f0-11c500cfc42d.png)

thank you

**Comment by theophane-girard** [comment]
My settings :
![image](https://user-images.githubusercontent.com/11314829/117420431-e2dd5300-af1d-11eb-88db-50d45a97ffb2.png)

**Comment by lgas** [comment]
It seems that sometimes (?) an empty entry "phpGettersSetters.templatesDir": "" is added to VSCode settings.json.
Error disapear with the entry removal.

**Comment by grosmanal** [comment]
I had the same issue when the property had a comment at the end of the line : 
``` php
    private int $myProperty // dummy comment
```
I just had to remove the comment and it works fine.

Hope this helps

**Comment by cvergne** [comment]
Lines with comment at the end should now be handled in v1.5.0 (pre-release, see #17).
If you can give it a try, please give me a feedback :)

**Comment by cvergne** [comment]
I close the issue as it should be fixed in v1.6.0 now.
Feel free to re-open if the bug is still here.
