### ISSUE TITLE
If PHP7 Type Hints is enabled, but property has no type declared, a colon is inserted after getter method.

### ISSUE THREAD

**Issue by AlexJBSilva** [cvergne/vscode-php-getters-setters#26]
https://github.com/cvergne/vscode-php-getters-setters/blob/f4cc160c359b1fc3b1308777be26d4d2429b44ba/src/extension.ts#L317

The method getReturnTypeHint stores an empty string in 'type' when a null is passed as first argument , and if PHP7 Type Hints is enabled, it will end up as a wrong colon inserted in getter function just after (), thus breaking the php code.

**Comment by cvergne** [comment]
Hello @AlexJBSilva 
Thanks for the report and PR. Could you just give me a code example of what you use as input, what you get (with the bug) and what do you expect to have ?

Thanks

**Comment by AlexJBSilva** [comment]
Sure! Here is a simple code example:
**Input:**
```
<?php

class ID
{
    private $value;

    public function __construct($value)
    {
        $this->value = $value;
    }
}
```
Then, we ask the extension to make its work:
![image](https://user-images.githubusercontent.com/104526833/165801185-36eb52b9-e6c4-445d-9517-55e75f3cab9c.png)

**Output (with the bug):**
```
<?php

class ID
{
    private $value;

    public function __construct($value)
    {
        $this->value = $value;
    }

    /**
     * Get the value of value
     */
    public function getValue(): 
    {
        return $this->value;
    }
}
```
![image](https://user-images.githubusercontent.com/104526833/165799425-45e1d07e-57c4-4f77-af84-a4f5489be17d.png)


**We expect to NOT have that colon.**
___________________________________________
Thank You for keeping this extension alive!

**Comment by cvergne** [comment]
Thanks for the quick reply and details 👌
Merged and new release on the way ;)
