### ISSUE TITLE
Not visible on Open VSX Registry

### ISSUE THREAD

**Issue by devbieres** [cvergne/vscode-php-getters-setters#3]
Hi,
It's seems that VSCodium is using a dedicated repo for extension : Open VSX Registry (https://open-vsx.org/).

Would you agree to publish your extension on it ?
A link : https://github.com/VSCodium/vscodium/issues/337#issuecomment-685731017

Thanks.

**Comment by cvergne** [comment]
Hi !
Didn't know about it, thanks !
I'll try to take a look tomorrow :)

**Comment by cvergne** [comment]
Hi,

Extension published on Open VSX Registry :
https://open-vsx.org/extension/cvergne/vscode-php-getters-setters-cv

And any new release will be automatically published on both Visual Studio Marketplace & Open VSX Registry

Thanks for the request :)
