### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by tdwesten** [cvergne/vscode-php-getters-setters#6]
He thanks for forking! But.. 

I got this error when running any of the 3 commands. 
`phpGettersSetters error: Cannot read property 'indexOf' of undefined`

Running; 
VSCODE; 1.53.0
Plugin version: v1.3.0

**Comment by cvergne** [comment]
Hi,

Are you using getters/setters template functionality ?
Does it bug on any kind of var declaration code ?

Thanks

**Comment by tdwesten** [comment]
@cvergne Thanks for responding, somehow its fixed after a hard restart 🎉
